apiVersion: v1
kind: Service
metadata:
  name: discord-bot-service
  labels:
    app: discord-app
spec:
  type: NodePort
  selector:
    app: discord-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
