apiVersion: v1
kind: Service
metadata:
  name: elonma-model-service
  labels:
    app: elonma-model
spec:
  type: ClusterIP
  selector:
    app: elonma-model
  ports:
    - port: 8081
      targetPort: 8081
