apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: server
      port: 5672
      targetPort: 5672
    - name: monitor
      port: 15672
      targetPort: 15672
