name: build-bot

on:
  push:
    tags:
      - 'bot*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Generate App Version
        run: |
          VERSION=`git describe --tags --always`
          echo APP_VERSION=${VERSION#bot} >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./bot
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cc-discord-bot:${{ env.APP_VERSION }}